### PR TITLE
AntiInstagram Cleanup and fixing

### PR DESCRIPTION
**Pull request by surirohit**
These first two commits are mostly cleaning up Anti-Instagram to contain only the parts which the Duckiebot actually uses. One more interesting fix but that is described in the next comment.  

- Removed the linear mode of operation which was not being used
- Removed the fancy geometry which was not being used
- Merged `cont_anti_instagram_node` and `image_transformer_node` into one since there was absolutely no need for two nodes
- Removed all the images which the actual project developers added
- Removed all other files (tests, libraries, etc) which were not being used

What is pending:
- Anti-Instagram can be made better. Ideas welcome
- Needs to be renamed
- Documentation pending
- Parameters need to go into config file

Results:
- Lane following tested, works the same as before
- CPU and RAM usage comparable

### CODE REVIEW

**Comment by surirohit** [comment]
Now where things get interesting. This is how the subscriber of `image_transformer_node` looked like in `devel20`

https://github.com/duckietown/dt-core/blob/2c529db092a66f8f39958316a3cf3f132a7fc7cb/packages/anti_instagram/src/image_transformer_node.py#L86-L97

Things to note about this:
- Queue size of subscriber is 1
- Creating threads will actually make the node process multiple images at the same time so that fewer frames are dropped, while ensuring that too old frames are not processed
- However, the function `cbNewImage` had a non-blocking lock which would return immediately if some other image was already being processed. So even if threads existed, they would simply not be executed as long as another one was executing. In fact, they wouldn't even wait for it to finish. 

The obvious thing to do was to remove this threading. I removed it and Voila!! My Duckiebot crashed into everything possible. Anti-Instagram was lagging in processing images by approximately 2 seconds. However, the processing was at the same fps as before.

**Comment by surirohit** [comment]
I started looking into how subscribing and publishing happen in ros and came across this snippet from the rospy Subscriber class:
```
        @param buff_size: incoming message buffer size in bytes. If
          queue_size is set, this should be set to a number greater
          than the queue_size times the average message size. Setting
          buff_size to a non-default value affects all subscribers to
          this topic in this process.
```
The `buff_size` by default is 65536 bytes, and the maximum size possible theoretically for our images is 921600 bytes. This was indeed the problem.

Multiple threads could still wait for the message to be completely received in chunks of 65536 bytes before actually heading for the callback. A single callback however would not start receiving a second message while the first was still being processed. I set the buffer size to 921600 and the timing of messages was comparable to `devel20` again. The CPU usage was slightly higher and the RAM usage was slightly lower. This brings me to my next commit.

**Comment by surirohit** [comment]
I went through all nodes inside `dt-core` some of which were using this threading style for non image messages as well. I removed threading for all subscribers and added the buffer size of 921600 bytes for all **image** subscribers leaving it to default for others. I am aware that after AI, the images are reduced size, so the buffer sizes can be adjusted accordingly

**Results of some experiments:-** 
Everything below is of the dt-core container only while running lane following

| What was done  | Frame Rate of Camera (fps) | Rate of output commands(Hz) | CPU Usage(%) | RAM Usage(MB) | 
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| devel20  | 30  | 11.0 | ~250 | ~600 |
| devel20 + AI without threading | 30 | 11.8 |  ~270 | ~510 |
| devel20 + everything without threading | 30 | 12.6 |  ~270 | ~500 |
| devel20 + everything without threading | 15 | 12.6 |  ~270 | ~460 |
| devel20 + everything without threading | 10 | 10 |  ~220 | ~450 |

Conclusions:
- Removing threading just from AI frees up 90MB RAM at the cost of absolute increase of CPU usage of 20%, while increasing rate of output
- Removing threading from everywhere also increases rate of output without affecting RAM and CPU significantly (compared to above, not devel20) 
- Lowering fps of camera from also frees up RAM in **dt-core** container. I went from 30fps to 15fps with no degrade in performance, and saved 40MB RAM. 
- We should probably find our maximum throughput once all the code is refactored and optimized and adjust the fps of camera accordingly.

**Comment by AleksandarPetrov** [comment]
@surirohit I don't really understand what the problem with the buff_size is. What happens if it is less than the actual message? And what happens if it is much more? For example, should we adjust it if, say, we decide to use higher resolution images at some point?

**Comment by surirohit** [comment]
This is my understanding of how subscribers work

- There is a buffer for communication where messages from the publisher are initially received. This has nothing to do with the queue and buffer size we set. This buffer should be big enough by default for us. 

- Then there is a buffer of the subscriber. This determines how much data comes from the socket (buffer of the OS) into the subscriber at once. This was the bottleneck. 


- What happens if it is much less? A message will not fit in the buffer size. You will need a lot of reads from the buffer before you get the complete message. 

- what happens if it is much more? If the queue size remains 1, then nothing changes except you use more RAM. If queue size is increased (we don't want this), then more messages fit into the buffer at once. 

- What happens if we use higher resolution? The current buffer size is 640x480x3 bytes which is the maximum possible size of the compressed image. If we use a higher resolution, we need to increase this size.

**Comment by surirohit** [comment]
Adding to what I said above, when the buffer size is too low, the subscriber queue will not work properly. While the messages are still in the socket buffer, the node will keep processing them, regardless of whether there are 50 messages in the socket buffer. This is because, as far as the node is concerned, there is only one message in its buffer.

**Pull request closed without merging**
