### PR TITLE
hsv values changed

### PR DESCRIPTION
**Pull request by surirohit**
## Description
Noticed that in the Autolab at ETH, validating the extrinsic calibration inside the city sometimes resulted in missed yellow detections. Updated HSV values and verified results.

## Type of change

Please mark the relevant options with X:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change is constrained only to one package, any interfaces to nodes from other packages are maintained
- [ ] This change is constrained only to packages in this repository, any interfaces to nodes from other repositories are maintained
- [ ] This change required a documentation update
- [ ] This change is only a documentation update
- [ ] This change restructures the repository (at level higher than package level)
- [ ] This change requires a change in the Duckiebook (if yes, please describe and, if possible, make a pull request for an edit in the book and link it here)

## Tests

Please describe all tests ran and their outcome. It is highly recommended that you at least do the tests listed by default, even if you only changed the documentation.

- [X] Made the Duckiebot move with keyboard control
- [X] Visually checked the published camera stream
- [X] Verified that the lane following demo works
- [X] Verified that the indefinite navigation demo works

## Style compliance
Please make sure that all your changes conform to the Duckietown (code style)[link] and code (documentation style)[link] guidelines:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I checked that this pull request is compliant with the Duckietown code style
- [ ] I checked that this pull request is compliant with the Duckietown code documentation style

## Next steps
Please describe if you have any questions, comments, or doubts towards the Duckietown software guardians regarding implementation, code style, running tests, documentation, etc.

## FOR THE REVIEWERS
__IMPORTANT:__ DO NOT CHANGE THIS SECTION!

- [ ] Functionality (is the change necessary and is it implemented in the most appropriate way): @liampaull or @afdaniele
- [ ] Integration testing (verify the tests and run additional if necessary): @?
- [ ] Code style compliance: @gibernas
- [ ] Documentation compliance: @aleksandarpetrov

_To the reviewers:_ If you deem necessary, request code edits, more tests, documentation update, or additional reviewing. __Do not review your own code!__

_PR Template, last edit 23 Aug 2019_

### CODE REVIEW

**Comment by surirohit** [comment]
Removed the yellowish part (Hue values 10-15)
Red range earlier:
image

Red range now:
image


Modified range of yellowish part:
Earlier:
image
Now:
image

**Comment by surirohit** [comment]
Mostly by observation. I saw some dark yellow tape being detected as red at the border so I trimmed the hue there. Decreases the lower limit of yellow for the same reason.

**Comment by gibernas** [comment]
Would be great if you could write this down somewhere, with the images of color ranges

**Comment by liampaull** [comment]
Making things work inside the ETH Autolab is in general bad practice and results in overfitting to your setup and breaking for everyone else. Suggest not to merge.

**Comment by surirohit** [comment]
@liampaull

I completely agree with you. Maybe decreasing the higher hue value for yellow and red is a breaking change. My motivation behind those is purely based on observation. 

Decreasing the lower hue range for yellow seems necessary because that region is within the yellow range of tape we have at ETH. Adding a bit more range to yellow detection hopefully should not break anything since tape which was being detected as yellow earlier will continue to be detected.

**Comment by liampaull** [comment]
@surirohit keep in mind that it's in the range of tape you have at ETH conditional on the lighting that you have at ETH. The last time someone from your lab changed these values it broke the lane following for everyone else. I will try to test it.

**Comment by surirohit** [comment]
@liampaull 

If the lane following fails with these changes, it would be super helpful to have a bag file with just the camera topics to understand what went wrong. Could you please record a bag file in that case?

**Comment by surirohit** [comment]
@gibernas 
Write down what, where?

**Comment by liampaull** [comment]
Let's close this.

**Pull request closed without merging**
