### PR TITLE
Fix encoding of led_detector_node/image_detection(front, right, TL)

### PR DESCRIPTION
**Pull request by ItsTimmy**
## Description

Changed encoding of the topics `led_detector_node/image_detection_front`, `led_detector_node/image_detection_right`, and `led_detector_node/image_detection_TL` from `passthrough` to `bgr8` so it can be viewed with `rqt_image_view`.

## Type of change

Please mark the relevant options with X:

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change is constrained only to one package, any interfaces to nodes from other packages are maintained
- [ ] This change is constrained only to packages in this repository, any interfaces to nodes from other repositories are maintained
- [ ] This change required a documentation update
- [ ] This change is only a documentation update
- [ ] This change restructures the repository (at level higher than package level)
- [ ] This change requires a change in the Duckiebook (if yes, please describe and, if possible, make a pull request for an edit in the book and link it here)

## Tests

Please describe all tests ran and their outcome. It is highly recommended that you at least do the tests listed by default, even if you only changed the documentation.

- [X] Made the Duckiebot move with keyboard control
- [X] Visually checked the published camera stream
- [X] Verified that the lane following demo works
- [ ] Verified that the indefinite navigation demo works (It did not work before this change, and this change won't fix it)

## Style compliance
Please make sure that all your changes conform to the Duckietown (code style)[link] and code (documentation style)[link] guidelines:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I checked that this pull request is compliant with the Duckietown code style
- [X] I checked that this pull request is compliant with the Duckietown code documentation style

## Next steps
Please describe if you have any questions, comments, or doubts towards the Duckietown software guardians regarding implementation, code style, running tests, documentation, etc.

## FOR THE REVIEWERS
__IMPORTANT:__ DO NOT CHANGE THIS SECTION!

- [ ] Functionality (is the change necessary and is it implemented in the most appropriate way): @liampaull or @afdaniele
- [ ] Integration testing (verify the tests and run additional if necessary): @?
- [ ] Code style compliance: @gibernas
- [ ] Documentation compliance: @aleksandarpetrov

_To the reviewers:_ If you deem necessary, request code edits, more tests, documentation update, or additional reviewing. __Do not review your own code!__

_PR Template, last edit 23 Aug 2019_

### CODE REVIEW

**Comment by surirohit** [comment]
@afdaniele 
Approved for merging

**Comment by afdaniele** [comment]
@ItsTimmy can you check what the original encoding is? I'm not sure we want to re-encode 3 image topics (maybe at 30fps), we should check the impact of this on the CPU.

**Comment by liampaull** [comment]
@gibernas can you look at the status of this PR? Probably what you have done recently supersedes it.

**Comment by liampaull** [comment]
obsolete due to recent developments

**Pull request closed without merging**
