### PR TITLE
AntiInstagram Cleanup and fixing

### PR DESCRIPTION
**Pull request by surirohit**
## Description

Please go through https://github.com/duckietown/dt-core/pull/9 for detailed information about this pull request

## Type of change

Please mark the relevant options with X:

- [X] Improvement
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change is constrained only to one package, any interfaces to nodes from other packages are maintained
- [X] This change is constrained only to packages in this repository, any interfaces to nodes from other repositories are maintained
- [ ] This change required a documentation update
- [ ] This change is only a documentation update
- [ ] This change restructures the repository (at level higher than package level)
- [ ] This change requires a change in the Duckiebook (if yes, please describe and, if possible, make a pull request for an edit in the book and link it here)

## Tests

Please describe all tests ran and their outcome. It is highly recommended that you at least do the tests listed by default, even if you only changed the documentation.

- [X] Made the Duckiebot move with keyboard control
- [X] Visually checked the published camera stream
- [X] Verified that the lane following demo works
- [ ] Verified that the indefinite navigation demo works

## Style compliance
Please make sure that all your changes conform to the Duckietown (code style)[link] and code (documentation style)[link] guidelines:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I checked that this pull request is compliant with the Duckietown code style
- [ ] I checked that this pull request is compliant with the Duckietown code documentation style

## Next steps
Please describe if you have any questions, comments, or doubts towards the Duckietown software guardians regarding implementation, code style, running tests, documentation, etc.

## FOR THE REVIEWERS
__IMPORTANT:__ DO NOT CHANGE THIS SECTION!

- [ ] Functionality (is the change necessary and is it implemented in the most appropriate way): @liampaull or @afdaniele
- [ ] Integration testing (verify the tests and run additional if necessary): @?
- [ ] Code style compliance: @gibernas
- [ ] Documentation compliance: @aleksandarpetrov

_To the reviewers:_ If you deem necessary, request code edits, more tests, documentation update, or additional reviewing. __Do not review your own code!__

_PR Template, last edit 23 Aug 2019_

### CODE REVIEW

**Comment by liampaull** [comment]
@surirohit can you have a look at the conflict?

**Comment by AmaurX** [comment]
> @surirohit can you have a look at the conflict?

@liampaull I solved it, it was a missing empty line

**Comment by afdaniele** [comment]
I've got a few questions:
- why did we remove the annotation tool? was it used by anyone?
- why did we remove the unit tests?
- if we remove the annotation tool, unlist it from `.dockerignore`

**Comment by surirohit** [comment]
**Annotation tool**
It looks like it was used to get colors of various parts of the road for the k-means step of AntiInstagram. That step has been removed since it was not being used. If we want to keep this tool, maybe we should move it somewhere else just to keep dt-core clean. It exists in Software anyway.

**Unit tests**
- `antiinstagram_correctness_test.py`: K-means stuff
- `antiinstagram_performance_test.py`: K-means stuff
- `antiinstagram_stub_test.py`: K-means stuff
- `decode_test.py`: belongs in duckietown-utils, not here 

**.dockerignore**
Will do!

**Comment by liampaull** [comment]
I'm scared to merge a PR that modifies 252 files...

**Comment by gibernas** [comment]
many of them are image deletions though

**Pull request merged**
